version: '3'

services:
  cvscan-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - ./cv_dummy:/app/cv_dummy:rw
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  model-data:
    driver: local