version: '3'

services:
  cvscan-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the entire directory to ensure all paths are preserved
      - .:/app
    restart: unless-stopped
    environment:
      - TZ=UTC