version: '3'

services:
  cvscan-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount directories to access pickle files
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - ./cv_dummy:/app/cv_dummy:rw
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
