version: '3'

services:
  cvscan-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the entire directory to ensure all paths are preserved
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
